#!/usr/bin/env sh
# monitor-switch - manage monitor layout, scale and power via hyprctl.
# Usage: monitor-switch.sh [--status|--list-modes <monitor>|--set <monitor> <key> <value>|--apply]
# Keys: scale, power (on/off)
# shellcheck disable=SC1091

set -u

ARGVUS_BOOTSTRAP="${ARGVUS_BOOTSTRAP:-${ARGVUS_SYSTEM_CONFIG:-/usr/share/argvus}/argvus/sh/bootstrap.sh}"
. "$ARGVUS_BOOTSTRAP"
ARGVUS_MUTABLE_CONFIG=1

STATE_DIR="${ARGVUS_CONFIG_HOME}/argvus"
STATE_FILE="${STATE_DIR}/.monitors"
MONITORS_LUA="$(paths_config hypr/monitors.lua)"
NWG_MONITORS_CONF="${HOME}/.config/hypr/monitors.conf"

# Validate a monitor exists in the current layout.
monitor_exists() {
  hyprctl monitors -j 2>/dev/null | grep -q "\"name\": \"$1\""
}

# List connected monitor names.
list_monitors() {
  hyprctl monitors -j 2>/dev/null | grep -o '"name": "[^"]*"' | sed 's/"name": "//; s/"$//'
}

print_status() {
  hyprctl monitors -j 2>/dev/null | python3 -c '
import sys, json
try:
    data = json.load(sys.stdin)
except Exception:
    sys.exit(0)
for m in data:
    name = m.get("name", "")
    res = "%dx%d@%d" % (m.get("width", 0), m.get("height", 0), m.get("refreshRate", 0))
    pos = "%d,%d" % (m.get("x", 0), m.get("y", 0))
    scale = m.get("scale", 1)
    power = "off" if m.get("dpmsStatus", False) is False else "on"
    print("name=%s" % name)
    print("res=%s" % res)
    print("pos=%s" % pos)
    print("scale=%s" % scale)
    print("power=%s" % power)
'
}

set_key() {
  _monitor="$1"
  _key="$2"
  _value="$3"

  monitor_exists "$_monitor" || { printf 'Monitor not found: %s\n' "$_monitor" >&2; return 1; }

  case "$_key" in
    scale)
      case "$_value" in
        *[!0-9.]*|'') printf 'Invalid scale: %s\n' "$_value" >&2; return 1 ;;
      esac
      hyprctl keyword monitor "$_monitor",preferred,auto,"$_value" >/dev/null 2>&1
      _persist "$_monitor" "scale" "$_value"
      write_lua
      ;;
    power)
      case "$_value" in
        on|off) ;;
        *) printf 'Invalid power: %s (use on|off)\n' "$_value" >&2; return 1 ;;
      esac
      hyprctl dispatch dpms "$_value" "$_monitor" >/dev/null 2>&1
      _persist "$_monitor" "power" "$_value"
      ;;
    *)
      printf 'Invalid key: %s (scale|power)\n' "$_key" >&2; return 1 ;;
  esac

  printf 'Applied %s=%s on %s\n' "$_key" "$_value" "$_monitor"
}

# Remove an existing key for the monitor from state.
_persist() {
  _monitor="$1"; _key="$2"; _value="$3"
  mkdir -p "$STATE_DIR"
  _tmp="${STATE_FILE}.tmp"
  rm -f "$_tmp"
  [ -f "$STATE_FILE" ] || : > "$_tmp"
  # Keep other entries, drop same monitor+key if present.
  if [ -f "$STATE_FILE" ]; then
    while IFS= read -r _line; do
      case "$_line" in
        "$_monitor.$_key="*) continue ;;
        *) printf '%s\n' "$_line" ;;
      esac
    done < "$STATE_FILE" > "$_tmp"
  fi
  printf '%s.%s=%s\n' "$_monitor" "$_key" "$_value" >> "$_tmp"
  mv "$_tmp" "$STATE_FILE"
}

# Regenerate monitors.lua override from persisted scale entries.
write_lua() {
  _dir="${MONITORS_LUA%/*}"
  mkdir -p "$_dir"
  {
    printf '%s\n' '-- Generated by monitor-switch.sh -- persisted monitor settings.'
    printf '%s\n' '-- Scale entries override per-monitor scaling.'
    [ -f "$STATE_FILE" ] &&
    while IFS= read -r _line; do
      [ -n "$_line" ] || continue
      _monitor="${_line%%.*}"
      _rest="${_line#*.}"
      _key="${_rest%%=*}"
      _val="${_rest#*=}"
      case "$_key" in
        scale)
          printf 'hl.monitor({ output = "%s", scale = %s })\n' "$_monitor" "$_val"
          ;;
      esac
    done < "$STATE_FILE"
    printf '%s\n' '-- End generated.'
  } > "$MONITORS_LUA"
}

# Apply persisted scales/powers from state file to monitors.lua override.
apply_state() {
  [ -f "$STATE_FILE" ] || return 0

  write_lua

  # Re-apply powers set to off (persisted as a flag) at startup.
  while IFS= read -r _line; do
    [ -n "$_line" ] || continue
    _monitor="${_line%%.*}"
    _rest="${_line#*.}"
    _key="${_rest%%=*}"
    _val="${_rest#*=}"
    if [ "$_key" = "power" ] && [ "$_val" = "off" ]; then
      hyprctl dispatch dpms off "$_monitor" >/dev/null 2>&1
    fi
  done < "$STATE_FILE"

  hyprctl reload >/dev/null 2>&1
}

# Apply the layout written by nwg-displays (~/.config/hypr/monitors.conf).
# nwg-displays emits plain Hyprland "monitor =" lines; translate them to
# `hyprctl keyword monitor` for runtime application.
apply_nwg_conf() {
  [ -f "$NWG_MONITORS_CONF" ] || return 0
  while IFS= read -r _line; do
    _line="$(printf '%s' "$_line" | sed 's/^[[:space:]]*//; s/#.*//')"
    [ -n "$_line" ] || continue
    case "$_line" in
      monitor=*)
        _arg="${_line#monitor=}"
        _arg="$(printf '%s' "$_arg" | sed 's/[[:space:]]*$//')"
        [ -n "$_arg" ] || continue
        hyprctl keyword monitor "$_arg" >/dev/null 2>&1
        ;;
    esac
  done < "$NWG_MONITORS_CONF"
  notify_send "Displays" "Layout from nwg-displays applied" 2>/dev/null || true
}

case "${1:-}" in
  --status)
    print_status
    ;;
  --list-modes)
    [ -n "${2:-}" ] || { printf 'Missing monitor\n' >&2; exit 1; }
    hyprctl monitors -j 2>/dev/null | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
except Exception:
    sys.exit(0)
for m in data:
    if m.get('name') == '$2':
        modes = m.get('modes', [])
        for mod in modes:
            w = mod.get('width'); h = mod.get('height'); r = mod.get('refreshRate')
            if w and h and r:
                print('%dx%d@%d' % (w, h, r))
        break
"
    ;;
  --set)
    [ -n "${2:-}" ] && [ -n "${3:-}" ] && [ -n "${4:-}" ] || { printf 'Missing monitor/key/value\n' >&2; exit 1; }
    set_key "$2" "$3" "$4"
    ;;
  --apply)
    apply_state
    ;;
  --apply-nwg)
    apply_nwg_conf
    ;;
  *)
    printf 'Usage: monitor-switch.sh [--status|--list-modes <monitor>|--set <monitor> <key> <value>|--apply|--apply-nwg]\n' >&2
    printf 'Keys: scale (0.5-3.0), power (on|off)\n' >&2
    ;;
esac
